	{ "mmSMUIO_GFX_MISC_CNTL", REG_MMIO, 0x00c8, 0, &mmSMUIO_GFX_MISC_CNTL[0], sizeof(mmSMUIO_GFX_MISC_CNTL)/sizeof(mmSMUIO_GFX_MISC_CNTL[0]), 0, 0 },
	{ "mmPWR_MISC_CNTL_STATUS", REG_MMIO, 0x0183, 1, &mmPWR_MISC_CNTL_STATUS[0], sizeof(mmPWR_MISC_CNTL_STATUS)/sizeof(mmPWR_MISC_CNTL_STATUS[0]), 0, 0 },
