	{ "mmUMCCH0_0_EccErrCntSel_ARCT", REG_MMIO, 0x0360, 1, &mmUMCCH0_0_EccErrCntSel_ARCT[0], sizeof(mmUMCCH0_0_EccErrCntSel_ARCT)/sizeof(mmUMCCH0_0_EccErrCntSel_ARCT[0]), 0, 0 },
	{ "mmUMCCH0_0_EccErrCnt_ARCT", REG_MMIO, 0x0361, 1, &mmUMCCH0_0_EccErrCnt_ARCT[0], sizeof(mmUMCCH0_0_EccErrCnt_ARCT)/sizeof(mmUMCCH0_0_EccErrCnt_ARCT[0]), 0, 0 },
	{ "mmMCA_UMC_UMC0_MCUMC_STATUST0_ARCT", REG_MMIO, 0x03c2, 1, &mmMCA_UMC_UMC0_MCUMC_STATUST0_ARCT[0], sizeof(mmMCA_UMC_UMC0_MCUMC_STATUST0_ARCT)/sizeof(mmMCA_UMC_UMC0_MCUMC_STATUST0_ARCT[0]), 1, 0 },
	{ "mmMCA_UMC_UMC0_MCUMC_ADDRT0_ARCT", REG_MMIO, 0x03c4, 1, &mmMCA_UMC_UMC0_MCUMC_ADDRT0_ARCT[0], sizeof(mmMCA_UMC_UMC0_MCUMC_ADDRT0_ARCT)/sizeof(mmMCA_UMC_UMC0_MCUMC_ADDRT0_ARCT[0]), 1, 0 },
