.TH UMR 1 "August 2019" "AMD (c) 2019" "User Manuals"
.SH NAME
umr \- AMDGPU Userspace Register Debugger
.SH DESCRIPTION
.B umr
is a tool to read and display, as well as write to AMDGPU device
MMIO, PCIE, SMC, and DIDT registers via userspace.  It can autodetect
and scan AMDGPU devices (SI and up).
.SH Device Selection
.IP "--instance, -i <number>"
Pick a device instance to work with.  Defaults to the 0'th device.  The instance
refers to a directory under
.B /sys/kernel/debug/dri/
where 0 is the first card probed.
.IP "--force, -f <number>"
Force a PCIE Device ID in hex or by asic name.  This is used in case the amdgpu driver
is not yet loaded or a display is not yet attached.  A '@' prefix will specify a path to
 an NPI script, for instance, '@/home/user/device.npi'.  A '.' prefix will specify a virtual
device which is handy for looking up register decodings for a device not present in the system,
for instance, '.vega10'.
.IP "--pci <device>"
Force a specific PCI device using the domain:bus:slot.function format in hex.
This is useful when more than one GPU is available. If the amdgpu driver is
loaded the corresponding instance will be automatically detected.
.IP "--update, -u <filename>"
Specify update file to add, change, or delete registers from the register
database.  Useful for adding registers that are not including in the kernel headers.

.IP "--option, -O <string>[,<string>,...]"
Specify options to the tool.  Multiple options can be specified as comma
separated strings.  Options should be specified before --update or --force commands
(among others) to enable options specified.

.B quiet
     Disable various informative but not required (for functionality) outputs.

.B read_smc
     Enable scanning of SMC registers.

.B bits
     enables displaying bitfields for scanned blocks.

.B bitsfull
     enables displaying bitfields using their entire path for scanned blocks.

.B empty_log
     Empties the MMIO log after reading it.

.B follow
     Causes the --logscan command to repeatedly produce output without
     exiting.

.B no_follow_ib
     Instruct the --ring command to not attempt to follow IBs pointed to by the packets
     in the ring.

.B named
     Causes --read to print out the register name with the register
     value.

.B many
     Allows matching regname openly (used with --read) and implies
     "named".  For instance "*.dce100.CRTC" would match any register that
     contains the fragment "CRTC" in the name.

.B use_pci
     Enable PCI access for MMIO instead of using debugfs.  Used by the --read,
     --scan, --top, --write, and --write-bit commands.  Does not currently
     support multiple instances of the same GPU (PCI device ID).  Note that access
     to non-MMIO registers might be disabled when using this flag.

.B use_colour
     Enable colour output for --top command, scales from blue, green, yellow, to red.  Also
     accepted is 'use_color'.

.B no_kernel
     Disable using kernel files to access the device.  Implies ''use_pci''.  This is meant to
     be used only if the KMD is hung or otherwise not working correctly.  Using it on live systems
     may result in race conditions.

.B verbose
     Enable verbose diagnostics (used in --vram).

.B halt_waves
     Halt/resume all waves while reading wave status.

.B disasm_early_term
     Terminate shader disassembly when first s_endpgm is hit.  This is required for
     older UMDs (or non-mesa UMDs) that don't use the quintuple 0xBF9F0000 to signal the true
     end of a shader.

.B no_disasm
     Disable shader disassembler logic (still outputs text just doesn't use LLVM to decode).  Useful
     if the linked llvm-dev doesn't support the hardware being debugged.  Avoids segfualts/asserts.

.B disasm_anyways
     Enable shader disassembly in --waves even if the rings aren't halted.

.B wave64
     Enable full 64 wave disassembly

.B full_shader
     Enable full shader disassembly in --waves when '-O bits' is used and the shader is found in
     a gfx or compute ring.

.SH Bank Selection
.IP "--bank, -b <se> <sh> <instance>"
Select a GRBM se/sh/instance bank in decimal.  Can use 'x' to denote a broadcast selection.
.IP "--sbank, -sb <me> <pipe> <queue> [vmid]"
Select a SRBM me/pipe/queue bank in decimal.  VMID is optional (default: 0).
.IP "--cbank, -cb <context_reg_bank>"
Select a context register bank (value is multiplied by 0x1000).  Used for context registers
in the range 0xA000..0xAFFF.
.IP "--hw-inst, -hw <instance>"
Select a SOC15 IP block instance.  (Default: 0)
.SH Device Information
.IP "--config, -c"
Print out configuation data read from kernel driver.
.IP "--enumerate, -e"
Enumerate all AMDGPU supported devices.
.IP "--list-blocks -lb"
List all blocks attached to the asic that has been detected.
.IP "--list-regs, -lr <string>"
List all registers in an IP block (can use '-O bits' to list bitfields)

.SH Register Access
.IP "--lookup, -lu <address_or_regname> <number>"
Look up an MMIO register by address and bitfield decode the value specified (with 0x prefix) or by
register name.  The register name string must include the ipname, e.g., uvd6.mmUVD_CONTEXT_ID.
.IP "--write -w <string> <number>"
Write a value specified in hex to a register specified with a complete
register path in the form <
.B asicname.ipname.regname
>.  For example, fiji.uvd6.mmUVD_CGC_GATE.  The value of asicname and/or ipname can be
.B *
to simplify scripting.  This command can be used multiple times to
write to multiple registers in a single invocation.
.IP "--writebit -wb <string> <number>"
Write a value specified in hex to a register bitfield specified with a
complete register path as in the
.B --write
command.
.IP "--read, -r <string>"
Read a value from a register specified by a register path to stdout.
This command uses the same syntax as the
.B --write
command but also allows
.B *
for the regname field to read an entire block.  Additionally,
a
.B *
can be appended to a register name to read any register that contains
a partial match.  For instance, "*.vcn10.ADDR*" would read any register
from the 'VCN10' block which contains 'ADDR' in the name.
.IP "--scan, -s <string>"
Scan and print an IP block by name, for example,
.B uvd6
or
.B carrizo.uvd6.
Can be used multiple times in a single invocation.

.SH Device Utilization
.IP "--top, -t"
Summarize GPU utilization.  Can select a SE block with --bank.  Relevant
options that apply are:
.B use_colour
and
.B use_pci
.
.IP "--waves, -wa <ring_name>"
Print out information about any active CU waves.  Note that if GFX power gating
is enabled this command may result in a GPU hang.  It's unlikely unless you're
invoking it very rapidly.  Unlike the wave count reading in --top this command
will operate regardless of whether GFX PG is enabled or not.  Can use
.B bits
to decode the wave bitfields.  An optional ring name can be specified
(default: gfx) to search for pointers to active shaders to find extra debugging
information.
.IP "--profiler, -prof [pixel= | vertex= | compute=]<nsamples> [ring]"
Capture 'nsamples' samples of wave data.  Optionally specify a ring to use when
searching for IBs that point to shaders.  Defaults to 'gfx'.  Additionally, the type
of shader can be selected for as well to only profile a given type of shader.

.SH Virtual Memory Access
VMIDs are specified in umr as 16 bit numbers where the lower 8 bits indicate the hardware
VMID and the upper 8 bits indicate the which VM space to use.

.B	0 - GFX hub

.B	1 - MM hub

.B      2 - VC0 hub

.B      3 - VC1 hub


For instance, 0x107 would specify the 7'th VMID on the MM hub.


.IP "--vm-decode, -vm vmid@<address> <num_of_pages>"
Decode page mappings at a specified address (in hex) from the VMID specified.
The VMID can be specified in hexadecimal (with leading '0x') or in decimal.
Implies '-O verbose' for the duration of the command so does not require it
to be manually specified.

.IP "--vm-read, -vr [vmid@]<address> <size>"
Read 'size' bytes (in hex) from the address specified (in hexadecimal) from VRAM
to stdout.  Optionally specify the VMID (in decimal or in hex with a 0x prefix)
treating the address as a virtual address instead.  Can use 'use_pci' to
directly access VRAM.

.IP "--vm-write, -vw [vmid@]<address> <size>"
Write 'size' bytes (in hex) to the address specified (in hexadecimal) to VRAM
from stdin.

.IP "--vm-disasm, -vdis [<vmid>@]<address> <size>"
Disassemble 'size' bytes (in hex) from a given address (in hex).  The size can be
specified as zero to have umr try and compute the shader size.

.SH Ring and PM4 Decoding
.IP "--ring, -R <string>(from:to)"
Read the contents of a ring named by the string without the
.B amdgpu_ring_
prefix.  By default it will read and display the entire ring.  A
starting and ending address can be specified in decimal or a '.' can
be used to indicate relative to the current
.B wptr
pointer.  For example, "-R gfx" would read the entire gfx ring,
"-R gfx[0:16]" would display the contents from 0 to 16 inclusively, and
"-R gfx[.]" or "-R gfx[.:.]" would display the last 32 words relative
to rptr.
.IP "--dump-ib, -di [vmid@]address length [pm]"
Dump an IB packet at an address with an optional VMID.  The length is specified
in bytes.  The type of decoder <pm> is optional and defaults to PM4 packets.
Can specify '3' for SDMA packets.
.IP "--dump-ib-file, -df filename [pm]"
Dump an IB stored in a file as a series of hexadecimal DWORDS one per line.
Optionally supply a PM type, can specify '3' for SDMA IBs or '4' for
PM4 IBs.  The default is PM4.
.IP "--logscan, -ls"
Read and display contents of the MMIO register log.  Usually specified
with '-O bits,follow,empty_log' to enable continual dumping of the trace
log.

.SH "Notes"

- The "Waves" field in the DRM section of --top only works if GFX PG has been disabled.  Otherwise,
GPU hangs occur frequently.  When PG is enabled it will read a constant 0.

.SH "Environmental Variables"

.B UMR_LOGGER
    Directory to output "umr.log" file when capturing samples with the --top command.
